export enum ApiEndopoint {
    FRONT_USER_INFO = "/videomng/v1/frontuserinfo",
    FRONT_USER_INFO_ID = "/videomng/v1/frontuserinfo/:id",
    FRONT_USER_LOGIN = "/videomng/v1/frontuserlogin",
    FRONT_USER_LOGOUT = "/videomng/v1/frontuserlogout",
    FRONT_USER_CHECK_AUTH = "/videomng/v1/frontusercheckauth",
    VIDEO_INFO = "/videomng/v1/videoinfo",
    VIDEO_INFO_ID = "/videomng/v1/videoinfo/:id",
    VIDEO_COMMENT_ID = "/videomng/v1/video/:videoId/comment",
    FAVORITE_VIDEO_COMMENT = "/videomng/v1/favoritevideo/:videoId/comment",
    FAVORITE_VIDEO = "/videomng/v1/favoritevideo",
    FAVORITE_VIDEO_ID = "/videomng/v1/favoritevideo/:id",
    FAVORITE_VIDEO_MEMO = "/videomng/v1/favoritevideomemo",
    FAVORITE_VIDEO_MEMO_ID = "/videomng/v1/favoritevideomemo/:id",
    SEARCH_COMMENT_BY_KEYWORD = "/videomng/v1/searchcommentbykeyword",
    BLOCK_COMMENT = "/videomng/v1/favoritevideo/:videoId/blockcomment",
    BLOCK_COMMENT_ID = "/videomng/v1/favoritevideo/:videoId/blockcomment/:commentId",
    FAVORITE_COMMENT = "/videomng/v1/favoritevideo/:videoId/favoritecomment",
    FAVORITE_COMMENT_ID = "/videomng/v1/favoritevideo/:videoId/favoritecomment/:commentId",
    VIDEO_CATEGORY = "/videomng/v1/videocategory",
    VIEW_STATUS = "/videomng/v1/viewstatus",
    TAG_INFO = "/videomng/v1/taginfo",
    FAVORITE_VIDEO_TAG = "/videomng/v1/favoritevideotag",
    FAVORITE_VIDEO_TAG_ID = "/videomng/v1/favoritevideotag/:id",
    FRONT_USER_PASSWORD_ID = "/videomng/v1/frontuserpassword/:id",
    FAVORITE_VIDEO_SORT = "/videomng/v1/favoritevideosort",
    CHANNEL_VIDEO_INFO_ID = "/videomng/v1/channelvideo/:id",
}