export enum ApiEndopoint {
    FRONT_USER_INFO = "/videomng/v1/volumes/frontuserinfo",
    FRONT_USER_LOGIN = "/videomng/v1/volumes/frontuserlogin",
    FRONT_USER_LOGOUT = "/videomng/v1/volumes/frontuserlogout",
    FRONT_USER_CHECK_AUTH = "/videomng/v1/volumes/frontusercheckauth",
    VIDEO_INFO = "/videomng/v1/volumes/videoinfo",
    VIDEO_INFO_ID = "/videomng/v1/volumes/videoinfo/:id",
    VIDEO_COMMENT_ID = "/videomng/v1/volumes/videocomment/:id",
    FAVORITE_VIDEO_COMMENT_ID = "/videomng/v1/volumes/favoritevideocomment/:id",
    FAVORITE_VIDEO = "/videomng/v1/volumes/favoritevideo",
    FAVORITE_VIDEO_ID = "/videomng/v1/volumes/favoritevideo/:id",
    FAVORITE_VIDEO_MEMO = "/videomng/v1/volumes/favoritevideomemo",
    FAVORITE_VIDEO_MEMO_ID = "/videomng/v1/volumes/favoritevideomemo/:id",
    SEARCH_COMMENT_BY_KEYWORD = "/videomng/v1/volumes/searchcommentbykeyword",
    BLOCK_COMMENT = "/videomng/v1/volumes/blockcomment",
    BLOCK_COMMENT_ID = "/videomng/v1/volumes/blockcomment/:id",
    FAVORITE_COMMENT = "/videomng/v1/volumes/favoritecomment",
    FAVORITE_COMMENT_ID = "/videomng/v1/volumes/favoritecomment/:id",
    VIDEO_CATEGORY = "/videomng/v1/volumes/videocategory",
    VIEW_STATUS = "/videomng/v1/volumes/viewstatus",
    TAG_INFO = "/videomng/v1/volumes/taginfo",
    FAVORITE_VIDEO_TAG = "/videomng/v1/volumes/favoritevideotag",
    FAVORITE_VIDEO_TAG_ID = "/videomng/v1/volumes/favoritevideotag/:id",
}